--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/05/2019 01:41:07 p. m.
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE proyectochachas;

--
-- Drop table `detallestock`
--
DROP TABLE IF EXISTS detallestock;

--
-- Drop table `merma`
--
DROP TABLE IF EXISTS merma;

--
-- Drop table `receta`
--
DROP TABLE IF EXISTS receta;

--
-- Drop table `producto`
--
DROP TABLE IF EXISTS producto;

--
-- Drop table `envio`
--
DROP TABLE IF EXISTS envio;

--
-- Drop table `responsable`
--
DROP TABLE IF EXISTS responsable;

--
-- Drop table `sucursal`
--
DROP TABLE IF EXISTS sucursal;

--
-- Drop table `insumo`
--
DROP TABLE IF EXISTS insumo;

--
-- Drop table `persona`
--
DROP TABLE IF EXISTS persona;

--
-- Set default database
--
USE proyectochachas;

--
-- Create table `persona`
--
CREATE TABLE persona (
  CodigoPersona varchar(255) NOT NULL,
  NombrePersona varchar(255) DEFAULT NULL,
  ApellidoPersona varchar(255) DEFAULT NULL,
  TelefonoPersona varchar(255) DEFAULT NULL,
  CargoPersona varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodigoPersona)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `insumo`
--
CREATE TABLE insumo (
  CodInsumo varchar(255) NOT NULL,
  NombreInsumo varchar(255) DEFAULT NULL,
  TipoInsumo varchar(255) DEFAULT NULL,
  CantidadInsumo int(11) DEFAULT NULL,
  PRIMARY KEY (CodInsumo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `sucursal`
--
CREATE TABLE sucursal (
  CodSucursal varchar(255) NOT NULL,
  NombreSucursal varchar(255) DEFAULT NULL,
  DireccionSucursal varchar(255) DEFAULT NULL,
  Latitud double DEFAULT NULL,
  Longitud double DEFAULT NULL,
  TelefonoSucursal int(11) DEFAULT NULL,
  PRIMARY KEY (CodSucursal)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `responsable`
--
CREATE TABLE responsable (
  CodPersona varchar(255) NOT NULL,
  CodSucursal varchar(255) NOT NULL,
  PRIMARY KEY (CodSucursal, CodPersona)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE responsable
ADD CONSTRAINT FK_responsable_CodPersona FOREIGN KEY (CodPersona)
REFERENCES persona (CodigoPersona) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE responsable
ADD CONSTRAINT FK_responsable_CodSucursal FOREIGN KEY (CodSucursal)
REFERENCES sucursal (CodSucursal) ON DELETE NO ACTION;

--
-- Create table `envio`
--
CREATE TABLE envio (
  CodOrigen varchar(255) DEFAULT NULL,
  CodDestino varchar(255) DEFAULT NULL,
  CodProducto varchar(255) DEFAULT NULL,
  CantidadEnvio int(11) DEFAULT NULL,
  FechaHora varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE envio
ADD CONSTRAINT FK_envio_CodDestino FOREIGN KEY (CodDestino)
REFERENCES sucursal (CodSucursal) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE envio
ADD CONSTRAINT FK_envio_CodOrigen FOREIGN KEY (CodOrigen)
REFERENCES sucursal (CodSucursal) ON DELETE NO ACTION;

--
-- Create table `producto`
--
CREATE TABLE producto (
  CodProducto varchar(255) NOT NULL,
  NombreProducto varchar(255) DEFAULT NULL,
  TipoProducto varchar(255) DEFAULT NULL,
  Cantidad int(11) DEFAULT NULL,
  PRIMARY KEY (CodProducto)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `receta`
--
CREATE TABLE receta (
  CodInsumo varchar(255) NOT NULL,
  CodProducto varchar(255) NOT NULL,
  CantidadReceta int(11) DEFAULT NULL,
  PRIMARY KEY (CodProducto, CodInsumo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE receta
ADD CONSTRAINT FK_receta_CodInsumo FOREIGN KEY (CodInsumo)
REFERENCES insumo (CodInsumo) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE receta
ADD CONSTRAINT FK_receta_CodProducto FOREIGN KEY (CodProducto)
REFERENCES producto (CodProducto) ON DELETE NO ACTION;

--
-- Create table `merma`
--
CREATE TABLE merma (
  CodSucursal varchar(255) NOT NULL,
  CodProducto varchar(255) NOT NULL,
  CantidadMerma int(11) DEFAULT NULL,
  FechaHora varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodSucursal, CodProducto)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE merma
ADD CONSTRAINT FK_merma_CodProducto FOREIGN KEY (CodProducto)
REFERENCES producto (CodProducto) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE merma
ADD CONSTRAINT FK_merma_CodSucursal FOREIGN KEY (CodSucursal)
REFERENCES sucursal (CodSucursal) ON DELETE CASCADE;

--
-- Create table `detallestock`
--
CREATE TABLE detallestock (
  CodSucursal varchar(255) NOT NULL,
  CodProducto varchar(255) NOT NULL,
  CantidadDetalle int(11) DEFAULT NULL,
  NombreProducto varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodSucursal, CodProducto)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detallestock
ADD CONSTRAINT FK_detallestock_CodProducto FOREIGN KEY (CodProducto)
REFERENCES producto (CodProducto) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detallestock
ADD CONSTRAINT FK_detallestock_CodSucursal FOREIGN KEY (CodSucursal)
REFERENCES sucursal (CodSucursal) ON DELETE NO ACTION;

-- 
-- Dumping data for table persona
--
-- Table proyectochachas.persona does not contain any data (it is empty)

-- 
-- Dumping data for table insumo
--
-- Table proyectochachas.insumo does not contain any data (it is empty)

-- 
-- Dumping data for table sucursal
--
-- Table proyectochachas.sucursal does not contain any data (it is empty)

-- 
-- Dumping data for table producto
--
-- Table proyectochachas.producto does not contain any data (it is empty)

-- 
-- Dumping data for table responsable
--
-- Table proyectochachas.responsable does not contain any data (it is empty)

-- 
-- Dumping data for table receta
--
-- Table proyectochachas.receta does not contain any data (it is empty)

-- 
-- Dumping data for table merma
--
-- Table proyectochachas.merma does not contain any data (it is empty)

-- 
-- Dumping data for table envio
--
-- Table proyectochachas.envio does not contain any data (it is empty)

-- 
-- Dumping data for table detallestock
--
-- Table proyectochachas.detallestock does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;